# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: driver-location-app_development
  username: 'postgres'
  password: 'postgres'
  host: localhost

test:
  <<: *default
  database: driver-location-app_test
  username: 'postgres'
  password: 'postgres'

production:
  <<: *default
  database: driver-location-app_production
  username: 'postgres'
  password: 'postgres'
